name: fact_checker
description: A Flutter fact-checking app with AI chatbot
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.3.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true